import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, Clock3, EyeOff, FileUp, ShieldAlert } from "lucide-react-native";
import * as DocumentPicker from "expo-document-picker";
import { useRouter } from "expo-router";
import { importerCatalogue, lireFileModeration, traiterSignalement, type LigneCatalogue, type SignalementModeration } from "../src/api/moderation";
import { Ecran } from "../src/composants/Ecran";
import { BoutonRond } from "../src/composants/communs";
import { couleurs, espaces, police, rayons, typo } from "../src/theme/tokens";

export default function Administration() {
  const insets=useSafeAreaInsets(),router=useRouter(),client=useQueryClient(); const file=useQuery({queryKey:["moderation"],queryFn:lireFileModeration,retry:false});
  const agir=async(s:SignalementModeration,d:"conserve"|"mise_a_confirmer"|"retiree")=>{try{await traiterSignalement(s.signalement_id,d);await client.invalidateQueries({queryKey:["moderation"]});}catch{Alert.alert("Action impossible","Vérifiez que votre compte est autorisé à modérer.");}};
  const choisirCsv=async()=>{try{const choix=await DocumentPicker.getDocumentAsync({type:["text/csv","text/comma-separated-values","application/vnd.ms-excel"],copyToCacheDirectory:true});if(choix.canceled)return;const texte=await(await fetch(choix.assets[0].uri)).text();const lignes=lireCsv(texte);if(!lignes.length)throw new Error();const resultat=await importerCatalogue(lignes);Alert.alert("Import terminé",`${resultat.importees} fiche(s) créée(s) en brouillon.${resultat.erreurs.length?` ${resultat.erreurs.length} ligne(s) à corriger.`:""}`);}catch{Alert.alert("Import impossible","Utilisez le modèle CSV Koté et vérifiez les colonnes obligatoires.");}};
  return <Ecran><ScrollView contentContainerStyle={[styles.contenu,{paddingTop:insets.top+espaces.xs,paddingBottom:insets.bottom+espaces.xl}]}><View style={styles.entete}><BoutonRond Icone={ArrowLeft} etiquette="Retour" onPress={()=>router.back()}/><View><Text style={styles.titre}>Modération</Text><Text style={styles.sous}>Signalements à vérifier</Text></View></View><Pressable style={styles.importer} onPress={()=>void choisirCsv()}><FileUp size={22} color={couleurs.surAccent}/><View><Text style={styles.importerTitre}>Importer un catalogue CSV</Text><Text style={styles.importerSous}>Les fiches seront créées en brouillon.</Text></View></Pressable>{file.isPending?<ActivityIndicator color={couleurs.accent}/>:file.isError?<View style={styles.vide}><ShieldAlert size={30} color={couleurs.fraicheurAVerifier}/><Text style={styles.texte}>Cet espace est réservé aux comptes de modération.</Text></View>:file.data?.length===0?<View style={styles.vide}><BadgeCheck size={32} color={couleurs.accentDoux}/><Text style={styles.texte}>Aucun signalement en attente.</Text></View>:file.data?.map(s=><Carte key={s.signalement_id} signalement={s} onAgir={agir}/>)}</ScrollView></Ecran>;
}
function lireCsv(texte:string):LigneCatalogue[]{const [entete,...lignes]=texte.replace(/^\uFEFF/,"").trim().split(/\r?\n/);const cols=entete.split(";").map(c=>c.trim().toLowerCase());return lignes.filter(Boolean).map(l=>{const v=l.split(";").map(x=>x.trim());const get=(n:string)=>v[cols.indexOf(n)]??"";return{nom:get("nom"),categorie:get("categorie"),telephone:get("telephone"),repere:get("repere"),latitude:Number(get("latitude").replace(",",".")),longitude:Number(get("longitude").replace(",",".")),description:get("description")};});}
function Carte({signalement:s,onAgir}:{signalement:SignalementModeration;onAgir:(s:SignalementModeration,d:"conserve"|"mise_a_confirmer"|"retiree")=>void}){return <View style={styles.carte}><Text style={styles.nom}>{s.nom_enseigne}</Text><Text style={styles.motif}>{s.motif.replace("_"," ")}</Text>{s.commentaire?<Text style={styles.texte}>{s.commentaire}</Text>:null}<View style={styles.actions}><Pressable style={styles.action} onPress={()=>onAgir(s,"conserve")}><BadgeCheck size={16} color={couleurs.accentDoux}/><Text style={styles.actionTexte}>Conserver</Text></Pressable><Pressable style={styles.action} onPress={()=>onAgir(s,"mise_a_confirmer")}><Clock3 size={16} color={couleurs.fraicheurAVerifier}/><Text style={styles.actionTexte}>Vérifier</Text></Pressable><Pressable style={styles.action} onPress={()=>onAgir(s,"retiree")}><EyeOff size={16} color={couleurs.fraicheurAVerifier}/><Text style={styles.actionTexte}>Retirer</Text></Pressable></View></View>}
const styles=StyleSheet.create({contenu:{paddingHorizontal:espaces.md,gap:espaces.md},entete:{flexDirection:"row",alignItems:"center",gap:espaces.sm},titre:{color:couleurs.textePrincipal,fontSize:typo.titre,fontFamily:police.demi},sous:{color:couleurs.texteSecondaire,fontSize:typo.repere,fontFamily:police.normal},importer:{minHeight:76,flexDirection:"row",alignItems:"center",gap:espaces.sm,padding:espaces.md,borderRadius:rayons.tuile,backgroundColor:couleurs.accent},importerTitre:{color:couleurs.surAccent,fontFamily:police.demi,fontSize:typo.corps},importerSous:{color:couleurs.surAccent,fontFamily:police.normal,fontSize:typo.libelle,opacity:.8},carte:{gap:espaces.xs,padding:espaces.md,borderRadius:rayons.tuile,backgroundColor:couleurs.surface1},nom:{color:couleurs.textePrincipal,fontFamily:police.demi,fontSize:18},motif:{color:couleurs.accentDoux,fontFamily:police.gras,fontSize:typo.libelle,textTransform:"uppercase"},texte:{color:couleurs.texteSecondaire,fontFamily:police.normal,fontSize:typo.repere,lineHeight:20},actions:{flexDirection:"row",gap:espaces.xs,flexWrap:"wrap",marginTop:espaces.xs},action:{minHeight:44,flexDirection:"row",alignItems:"center",gap:5,paddingHorizontal:10,borderRadius:rayons.pastille,backgroundColor:couleurs.surface2},actionTexte:{color:couleurs.textePrincipal,fontFamily:police.demi,fontSize:11},vide:{minHeight:240,alignItems:"center",justifyContent:"center",gap:espaces.sm,padding:espaces.lg}});
