import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ArrowLeft, ArrowRight, CircleCheck, UserRound } from "lucide-react-native";
import { useRouter } from "expo-router";

import { demanderCode, formaterTelephone, normaliserTelephone, seDeconnecter, verifierCode } from "../src/api/compte";
import { Ecran } from "../src/composants/Ecran";
import { BoutonRond } from "../src/composants/communs";
import { GrandBouton, GrandChamp } from "../src/composants/espace";
import { useSession } from "../src/hooks/useSession";
import { couleurs, espaces, police, rayons, typo } from "../src/theme/tokens";

export default function Profil() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const session = useSession();
  const [etape, setEtape] = useState<"numero" | "code">("numero"); const [saisie, setSaisie] = useState(""); const [numero, setNumero] = useState<string | null>(null); const [code, setCode] = useState(""); const [chargement, setChargement] = useState(false); const [erreur, setErreur] = useState<string | null>(null);
  const envoyer = async () => { const normalise = normaliserTelephone(saisie); if (!normalise) return setErreur("Entrez un numéro de téléphone valide."); setChargement(true); setErreur(null); try { await demanderCode(normalise); setNumero(normalise); setEtape("code"); } catch { setErreur("Le code n’a pas pu être envoyé. Réessayez dans un instant."); } finally { setChargement(false); } };
  const valider = async () => { if (!numero) return; setChargement(true); setErreur(null); try { await verifierCode(numero, code.trim()); } catch { setErreur("Ce code est incorrect. Vérifiez puis réessayez."); } finally { setChargement(false); } };
  return <Ecran><View style={[styles.contenu,{paddingTop:insets.top+espaces.xs,paddingBottom:insets.bottom+espaces.xl}]}><BoutonRond Icone={ArrowLeft} etiquette="Retour" onPress={()=>router.back()}/><View style={styles.icone}><UserRound size={34} color={couleurs.accentDoux}/></View>{session.connecte ? <><Text style={styles.titre}>Votre profil Koté</Text><Text style={styles.texte}>Votre numéro est vérifié. Il sert uniquement à protéger les commerçants des demandes automatisées et n’est jamais affiché publiquement.</Text><View style={styles.numero}><Text style={styles.numeroTexte}>{formaterTelephone(session.telephone ?? "")}</Text></View><GrandBouton libelle="Se déconnecter" Icone={ArrowRight} variante="secondaire" onPress={()=>void seDeconnecter()}/></> : <><Text style={styles.titre}>{etape === "numero" ? "Protégeons les contacts." : "Entrez le code reçu"}</Text><Text style={styles.texte}>{etape === "numero" ? "Un profil gratuit suffit. Les numéros des commerçants ne sont jamais visibles dans Koté." : `Un code a été envoyé au ${formaterTelephone(numero ?? "")}.`}</Text>{etape === "numero" ? <><GrandChamp libelle="Votre numéro" valeur={saisie} onChange={setSaisie} placeholder="90 00 01 02" clavier="phone-pad"/><GrandBouton libelle={chargement ? "Envoi…" : "Recevoir mon code"} Icone={ArrowRight} desactive={chargement} onPress={()=>void envoyer()}/></> : <><GrandChamp libelle="Code reçu" valeur={code} onChange={setCode} placeholder="000000" clavier="number-pad" maxLength={6}/><GrandBouton libelle={chargement ? "Vérification…" : "Valider mon profil"} Icone={CircleCheck} desactive={chargement || code.length < 4} onPress={()=>void valider()}/><Pressable onPress={()=>setEtape("numero")} style={styles.lien}><Text style={styles.lienTexte}>Changer de numéro</Text></Pressable></>}{erreur ? <Text style={styles.erreur}>{erreur}</Text> : null}</>}</View></Ecran>;
}
const styles=StyleSheet.create({contenu:{flex:1,paddingHorizontal:espaces.md,gap:espaces.md},icone:{width:76,height:76,borderRadius:38,backgroundColor:couleurs.surface2,alignItems:"center",justifyContent:"center",alignSelf:"center",marginTop:espaces.lg},titre:{color:couleurs.textePrincipal,fontFamily:police.gras,fontSize:30,lineHeight:36,textAlign:"center",marginTop:espaces.sm},texte:{color:couleurs.texteSecondaire,fontFamily:police.normal,fontSize:typo.corps,lineHeight:23,textAlign:"center",marginBottom:espaces.sm},numero:{padding:espaces.md,borderRadius:rayons.tuile,backgroundColor:couleurs.surface1,alignItems:"center"},numeroTexte:{color:couleurs.textePrincipal,fontFamily:police.demi,fontSize:18},lien:{minHeight:48,alignItems:"center",justifyContent:"center"},lienTexte:{color:couleurs.accentDoux,fontFamily:police.demi,fontSize:typo.repere},erreur:{color:couleurs.fraicheurAVerifier,fontFamily:police.moyen,fontSize:typo.repere,textAlign:"center"}});
