import { useEffect, useState } from "react";
import { Alert, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ArrowLeft, ArrowRight, Bell, CircleCheck, ShieldAlert, UserRound } from "lucide-react-native";
import { useRouter } from "expo-router";
import { demanderCode, desactiverMonCompte, formaterTelephone, lirePreferencesProfil, majPreferencesProfil, normaliserTelephone, seDeconnecter, supprimerMonCompte, verifierCode } from "../src/api/compte";
import { Ecran } from "../src/composants/Ecran";
import { BoutonRond } from "../src/composants/communs";
import { GrandBouton, GrandChamp } from "../src/composants/espace";
import { enregistrerNotificationsDistantes } from "../src/notifications";
import { useSession } from "../src/hooks/useSession";
import { couleurs, espaces, police, rayons, typo } from "../src/theme/tokens";

export default function Profil() {
  const router=useRouter(),insets=useSafeAreaInsets(),session=useSession();
  const [etape,setEtape]=useState<"numero"|"code">("numero"),[saisie,setSaisie]=useState(""),[numero,setNumero]=useState<string|null>(null),[code,setCode]=useState(""),[chargement,setChargement]=useState(false),[erreur,setErreur]=useState<string|null>(null),[notifications,setNotifications]=useState(false),[admin,setAdmin]=useState(false);
  useEffect(()=>{if(session.connecte)void lirePreferencesProfil().then(p=>{setNotifications(Boolean(p?.notifications_activees));setAdmin(Boolean(p?.est_admin));}).catch(()=>undefined);},[session.connecte]);
  const envoyer=async()=>{const n=normaliserTelephone(saisie);if(!n){setErreur("Entrez un numÃ©ro de tÃ©lÃ©phone valide.");return;}setChargement(true);try{await demanderCode(n);setNumero(n);setEtape("code");}catch{setErreur("Le code nâ€™a pas pu Ãªtre envoyÃ©.");}finally{setChargement(false);}};
  const valider=async()=>{if(!numero)return;setChargement(true);try{await verifierCode(numero,code.trim());}catch{setErreur("Ce code est incorrect.");}finally{setChargement(false);}};
  const changerNotifications=async(v:boolean)=>{setNotifications(v);try{if(v)await enregistrerNotificationsDistantes();await majPreferencesProfil({notifications_activees:v});}catch{setNotifications(!v);Alert.alert("Notifications indisponibles","Vous pourrez les activer plus tard.");}};
  const action=(titre:string,texte:string,faire:()=>Promise<void>)=>Alert.alert(titre,texte,[{text:"Annuler",style:"cancel"},{text:titre,style:"destructive",onPress:()=>void(async()=>{setChargement(true);try{await faire();router.replace("/");}catch{Alert.alert("Action impossible","RÃ©essayez avec une connexion active.");}finally{setChargement(false);}})()}]);
  return <Ecran><View style={[styles.contenu,{paddingTop:insets.top+espaces.xs,paddingBottom:insets.bottom+espaces.xl}]}><BoutonRond Icone={ArrowLeft} etiquette="Retour" onPress={()=>router.back()}/><View style={styles.icone}><UserRound size={34} color={couleurs.accentDoux}/></View>{session.connecte?<><Text style={styles.titre}>Votre profil KotÃ©</Text><Text style={styles.texte}>Votre numÃ©ro vÃ©rifiÃ© protÃ¨ge les contacts des commerÃ§ants.</Text><View style={styles.numero}><Text style={styles.numeroTexte}>{formaterTelephone(session.telephone??"")}</Text></View><View style={styles.ligne}><Bell size={21} color={couleurs.accentDoux}/><View style={styles.ligneTexte}><Text style={styles.ligneTitre}>Rappels utiles</Text><Text style={styles.ligneSous}>Confirmations et rÃ©ponses importantes.</Text></View><Switch value={notifications} onValueChange={v=>void changerNotifications(v)} trackColor={{true:couleurs.accent}}/></View>{admin?<GrandBouton libelle="Ouvrir la modÃ©ration" Icone={ShieldAlert} variante="secondaire" onPress={()=>router.push("/administration")}/>:null}<GrandBouton libelle="Se dÃ©connecter" Icone={ArrowRight} variante="secondaire" onPress={()=>void seDeconnecter().then(()=>router.replace("/"))}/><Pressable disabled={chargement} onPress={()=>action("DÃ©sactiver ce compte ?","Vous ne pourrez plus vous connecter. Le support pourra le rÃ©activer aprÃ¨s vÃ©rification.",desactiverMonCompte)} style={styles.danger}><Text style={styles.dangerTexte}>DÃ©sactiver temporairement mon compte</Text></Pressable><Pressable disabled={chargement} onPress={()=>action("Supprimer dÃ©finitivement ce compte ?","Votre profil sera effacÃ©. Les fiches restent en brouillon pour prÃ©server les adresses utiles.",supprimerMonCompte)} style={styles.danger}><Text style={styles.dangerTexte}>Supprimer mon compte</Text></Pressable></>:<><Text style={styles.titre}>{etape==="numero"?"ProtÃ©geons les contacts.":"Entrez le code reÃ§u"}</Text><Text style={styles.texte}>{etape==="numero"?"Un profil gratuit suffit.":`Un code a Ã©tÃ© envoyÃ© au ${formaterTelephone(numero??"")}.`}</Text>{etape==="numero"?<><GrandChamp libelle="Votre numÃ©ro" valeur={saisie} onChange={setSaisie} placeholder="90 00 01 02" clavier="phone-pad"/><GrandBouton libelle={chargement?"Envoiâ€¦":"Recevoir mon code"} Icone={ArrowRight} desactive={chargement} onPress={()=>void envoyer()}/></>:<><GrandChamp libelle="Code reÃ§u" valeur={code} onChange={setCode} placeholder="000000" clavier="number-pad" maxLength={6}/><GrandBouton libelle={chargement?"VÃ©rificationâ€¦":"Valider mon profil"} Icone={CircleCheck} desactive={chargement||code.length<4} onPress={()=>void valider()}/><Pressable onPress={()=>setEtape("numero")} style={styles.danger}><Text style={styles.lienTexte}>Changer de numÃ©ro</Text></Pressable></>}{erreur?<Text style={styles.erreur}>{erreur}</Text>:null}</>}</View></Ecran>;
}
const styles=StyleSheet.create({contenu:{flex:1,paddingHorizontal:espaces.md,gap:espaces.md},icone:{width:76,height:76,borderRadius:38,backgroundColor:couleurs.surface2,alignItems:"center",justifyContent:"center",alignSelf:"center",marginTop:espaces.lg},titre:{color:couleurs.textePrincipal,fontFamily:police.gras,fontSize:30,lineHeight:36,textAlign:"center"},texte:{color:couleurs.texteSecondaire,fontFamily:police.normal,fontSize:typo.corps,lineHeight:23,textAlign:"center"},numero:{padding:espaces.md,borderRadius:rayons.tuile,backgroundColor:couleurs.surface1,alignItems:"center"},numeroTexte:{color:couleurs.textePrincipal,fontFamily:police.demi,fontSize:18},ligne:{minHeight:76,flexDirection:"row",alignItems:"center",gap:espaces.sm,padding:espaces.md,borderRadius:rayons.tuile,backgroundColor:couleurs.surface1},ligneTexte:{flex:1},ligneTitre:{color:couleurs.textePrincipal,fontFamily:police.demi,fontSize:typo.corps},ligneSous:{color:couleurs.texteSecondaire,fontFamily:police.normal,fontSize:typo.libelle,marginTop:2},danger:{minHeight:44,alignItems:"center",justifyContent:"center"},dangerTexte:{color:couleurs.fraicheurAVerifier,fontFamily:police.demi,fontSize:typo.repere},lienTexte:{color:couleurs.accentDoux,fontFamily:police.demi,fontSize:typo.repere},erreur:{color:couleurs.fraicheurAVerifier,fontFamily:police.moyen,textAlign:"center"}});


