import { createRoot } from 'react-dom/client'
import { useEffect, useState, type ReactNode } from 'react'
import { ArrowRight, BadgeCheck, Check, ChevronRight, Compass, MapPin, Menu, MessageCircle, Search, ShieldCheck, Store, X } from 'lucide-react'
import './site-v3.css'

const nav = [{ href: '#/', label: 'Accueil' }, { href: '#/fonctionnement', label: 'Fonctionnement' }, { href: '#/commerces', label: 'Commerces' }, { href: '#/tarifs', label: 'Tarifs' }]

function Brand({ inverse = false }: { inverse?: boolean }) { return <a className={`brand-v3 ${inverse ? 'inverse' : ''}`} href="#/" aria-label="Koté, accueil"><img src="/images/kote-logo-2026.png" alt=""/><b>KOTÉ</b></a> }

function Header({ path }: { path: string }) { const [open, setOpen] = useState(false); return <header className="header-v3"><Brand/><nav>{nav.map(item => <a className={item.href === path ? 'active' : ''} href={item.href} key={item.href}>{item.label}</a>)}</nav><a className="header-cta" href="#/commerces">Référencer mon commerce <ArrowRight size={15}/></a><button className="menu-v3" aria-label="Ouvrir le menu" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button>{open && <div className="mobile-v3">{nav.map(item => <a href={item.href} onClick={() => setOpen(false)} key={item.href}>{item.label}<ChevronRight size={16}/></a>)}<a href="#/commerces" onClick={() => setOpen(false)}>Référencer mon commerce <ArrowRight size={16}/></a></div>}</header> }

function Action({ children, muted = false, href = '#/fonctionnement' }: { children: ReactNode, muted?: boolean, href?: string }) { return <a className={`action-v3 ${muted ? 'muted' : ''}`} href={href}>{children}<ArrowRight size={17}/></a> }

function ProductCard() { return <div className="product-card"><div className="product-top"><span><i/> Koté autour de vous</span><b>12:42</b></div><div className="product-search"><Search size={17}/><span>Que cherchez-vous ?</span></div><div className="product-route"><span className="route-pin">●</span><span/><span className="route-pin small">●</span></div><article><div className="merchant-icon">A</div><div><b>Atelier Afiavi</b><small><MapPin size={11}/> À 400 m · Couture</small></div><BadgeCheck size={18}/></article><div className="product-status"><span/> Actif maintenant <b>Itinéraire <ArrowRight size={13}/></b></div></div> }

function Home() { return <><section className="hero-v3"><div className="hero-copy-v3"><p className="eyebrow-v3"><i/> LE QUARTIER, EN CLAIR</p><h1>Tout ce qui compte,<br/><em>juste à côté.</em></h1><p className="hero-description">Koté rend les commerces, artisans et bonnes adresses de Lomé faciles à trouver — sans détour, sans information floue.</p><div className="hero-actions-v3"><Action>Explorer Koté</Action><Action muted href="#/commerces">Je tiens un commerce</Action></div><div className="hero-meta"><span><ShieldCheck size={16}/> Contacts protégés</span><span><BadgeCheck size={16}/> Fiches vérifiées</span></div></div><div className="hero-object-v3"><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="hero-image-v3"><img src="/images/kote-lome-market-hero.png" alt="Des habitantes de Lomé retrouvent un commerce de quartier"/></div><ProductCard/><p className="object-label">LOMÉ / TOGO<br/>UNE ADRESSE AU BON MOMENT</p></div></section><section className="value-v3"><p>Le commerce local ne devrait pas être<br/><em>un secret bien gardé.</em></p><span>01 / L’ESSENTIEL</span></section><section className="snapshot-v3"><div className="section-head-v3"><p className="eyebrow-v3"><i/> SIMPLE PAR NATURE</p><h2>Trois gestes.<br/><em>Une vraie rencontre.</em></h2></div><div className="snapshot-steps"><article><span>01</span><Search/><h3>Cherchez</h3><p>Une activité, un produit ou un service près de vous.</p></article><article><span>02</span><Compass/><h3>Repérez</h3><p>Des indications de quartier que vous comprenez vraiment.</p></article><article><span>03</span><MessageCircle/><h3>Échangez</h3><p>Contactez directement la bonne personne, au bon moment.</p></article></div><Action href="#/fonctionnement">Voir comment Koté fonctionne</Action></section><section className="proof-v3"><div><p className="eyebrow-v3 inverse"><i/> UNE CONFIANCE LISIBLE</p><h2>On ne vous demande pas<br/>de croire. <em>On vous montre.</em></h2></div><div className="proof-list"><p><BadgeCheck/><span><b>Confirmée récemment</b> L’activité reste suivie.</span></p><p><ShieldCheck/><span><b>Vérifiée sur le terrain</b> Le repère existe réellement.</span></p><p><MessageCircle/><span><b>Contact sous contrôle</b> Votre profil protège l’échange.</span></p></div></section><section className="merchant-v3"><div className="merchant-symbol"><img src="/images/kote-logo-2026.png" alt=""/><span>VOTRE<br/>VISIBILITÉ</span></div><div><p className="eyebrow-v3"><i/> VOUS TENEZ UN COMMERCE ?</p><h2>Votre quartier<br/>vous cherche déjà.</h2><p>Une présence claire. Vos horaires, vos photos, vos repères. Vous gardez la main sur votre activité.</p><Action href="#/commerces">Découvrir l’espace commerce</Action></div></section></> }

const pageContent: Record<string, { eyebrow: string, title: ReactNode, lead: string, cards: Array<[string, string, typeof Search]> }> = {
  '#/fonctionnement': { eyebrow: 'LE FONCTIONNEMENT', title: <>Un trajet plus court.<br/><em>Un quartier plus proche.</em></>, lead: 'Koté prend les informations utiles et les rend visibles au moment où vous en avez besoin.', cards: [['Chercher', 'Dites simplement ce que vous cherchez.', Search], ['Choisir', 'Comparez les repères, horaires et informations suivies.', Compass], ['Contacter', 'Échangez avec le commerce sans rendre son numéro public.', MessageCircle]] },
  '#/commerces': { eyebrow: 'POUR LES COMMERÇANTS', title: <>Votre adresse mérite<br/><em>d’être trouvée.</em></>, lead: 'Koté transforme votre présence locale en fiche utile, claire et rassurante pour les habitants du quartier.', cards: [['Créer', 'Présentez votre activité, vos horaires et vos repères.', Store], ['Certifier', 'Faites vérifier votre activité lors d’un passage terrain.', ShieldCheck], ['Grandir', 'Choisissez une mise en avant locale quand vous en avez besoin.', BadgeCheck]] },
  '#/a-propos': { eyebrow: 'NOTRE MISSION', title: <>La vie locale<br/><em>en première ligne.</em></>, lead: 'Nous voulons que les commerces et les services qui font vivre Lomé soient aussi simples à retrouver qu’ils sont essentiels au quotidien.', cards: [['Local', 'Des repères ancrés dans les usages de chaque quartier.', MapPin], ['Direct', 'Une relation entre habitant et commerce, sans intermédiaire.', MessageCircle], ['Transparent', 'Des signaux de confiance simples, jamais opaques.', ShieldCheck]] },
}

function DetailPage({ data }: { data: typeof pageContent[string] }) { return <section className="detail-v3"><div className="detail-intro"><p className="eyebrow-v3"><i/> {data.eyebrow}</p><h1>{data.title}</h1><p>{data.lead}</p></div><div className="detail-cards">{data.cards.map(([title, text, Icon], index) => <article key={title}><span>0{index + 1}</span><Icon/><h2>{title}</h2><p>{text}</p></article>)}</div></section> }

const offers = [{ name: 'Essentiel', price: '0', desc: 'Pour être trouvé, simplement.', points: ['Fiche commerce', 'Repère et horaires', 'Demandes de contact protégées'] }, { name: 'Koté Pro', price: '3 000', desc: 'Pour devenir l’adresse de référence.', points: ['Tout Essentiel', 'Certification terrain', 'Photos et statistiques', 'Mise en avant locale'], featured: true }, { name: 'Koté Pro+', price: '7 500', desc: 'Pour les commerces qui accélèrent.', points: ['Tout Koté Pro', 'Plusieurs points de vente', 'Promotions locales', 'Support prioritaire'] }]
function PricingPage() { return <section className="pricing-v3"><div className="pricing-intro-v3"><p className="eyebrow-v3"><i/> DES OFFRES CLAIRES</p><h1>Être visible.<br/><em>Rester libre.</em></h1><p>Les habitants utilisent Koté gratuitement. Chaque commerce choisit le niveau d’accompagnement qui lui convient.</p></div><div className="pricing-grid-v3">{offers.map(offer => <article className={offer.featured ? 'featured' : ''} key={offer.name}>{offer.featured && <b className="offer-chip">LE PLUS CHOISI</b>}<h2>{offer.name}</h2><p className="offer-price"><strong>{offer.price}</strong> FCFA <small>/ mois</small></p><p className="offer-desc">{offer.desc}</p><ul>{offer.points.map(point => <li key={point}><Check size={15}/>{point}</li>)}</ul><Action href="#/commerces">Choisir cette offre</Action></article>)}</div><p className="cert-note"><BadgeCheck size={18}/> La certification Koté repose sur une vérification réelle sur le terrain — elle ne s’achète pas seule.</p></section> }

function NotFound() { return <section className="not-found-v3"><p className="eyebrow-v3"><i/> 404</p><h1>Cette adresse n’est pas<br/><em>dans le quartier.</em></h1><Action href="#/">Revenir à l’accueil</Action></section> }
function Footer() { return <footer className="footer-v3"><div><Brand inverse/><p>Les bonnes adresses du quartier, enfin visibles.</p></div><div className="footer-links-v3"><section><b>Découvrir</b><a href="#/fonctionnement">Fonctionnement</a><a href="#/a-propos">Notre mission</a></section><section><b>Commerces</b><a href="#/commerces">Créer ma fiche</a><a href="#/tarifs">Tarifs et options</a></section></div><small>© 2026 Koté · Lomé, Togo <span>Le quartier vous répond.</span></small></footer> }
function App() { const [path, setPath] = useState(location.hash || '#/'); useEffect(() => { const update = () => setPath(location.hash || '#/'); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, []); const page = path === '#/' ? <Home/> : path === '#/tarifs' ? <PricingPage/> : pageContent[path] ? <DetailPage data={pageContent[path]}/> : <NotFound/>; return <><Header path={path}/><main>{page}</main><Footer/></> }
createRoot(document.getElementById('app')!).render(<App />)
