import { Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ChevronRight, ImageOff, ShieldAlert, X } from "lucide-react-native";
import { useSignalementImage } from "../../src/hooks/useActions";
import type { MotifImage } from "../../src/api/actions";
import { couleurs, espaces, police, rayons, typo } from "../../src/theme/tokens";
const options:{motif:MotifImage;libelle:string}[]=[{motif:"violence",libelle:"Violence ou contenu choquant"},{motif:"harcelement",libelle:"Harcèlement ou atteinte à une personne"},{motif:"nudite",libelle:"Nudité ou contenu sexuel"},{motif:"arnaque",libelle:"Arnaque ou tromperie"},{motif:"hors_sujet",libelle:"Image sans rapport avec le commerce"}];
export default function Contenu(){const {id,chemin}=useLocalSearchParams<{id:string;chemin:string}>(),router=useRouter(),insets=useSafeAreaInsets(),signalement=useSignalementImage();const fermer=()=>router.canGoBack()?router.back():router.replace("/");const envoyer=(motif:MotifImage)=>{if(!id||!chemin)return;signalement.mutate({marchandId:id,chemin,motif},{onSuccess:()=>{setTimeout(fermer,900)}})};return <View style={styles.voile}><Pressable style={{flex:1}} onPress={fermer}/><View style={[styles.feuille,{paddingBottom:insets.bottom+espaces.lg}]}><View style={styles.poignee}/><View style={styles.entete}><View style={{flex:1}}><Text style={styles.titre}>Signaler cette image</Text><Text style={styles.sous}>Les signalements sont privés et examinés par Koté.</Text></View><Pressable style={styles.fermer} onPress={fermer}><X size={20} color={couleurs.texteSecondaire}/></Pressable></View>{signalement.isSuccess?<Text style={styles.confirmation}>Merci. Nous allons examiner cette image.</Text>:<View style={styles.options}>{options.map(o=><Pressable key={o.motif} style={styles.option} onPress={()=>envoyer(o.motif)} disabled={signalement.isPending}><ImageOff size={19} color={couleurs.accentDoux}/><Text style={styles.optionTexte}>{o.libelle}</Text><ChevronRight size={19} color={couleurs.texteSecondaire}/></Pressable>)}</View>}{signalement.isError?<Text style={styles.erreur}>Impossible d'envoyer le signalement.</Text>:null}</View></View>}
const styles=StyleSheet.create({voile:{flex:1,justifyContent:"flex-end",backgroundColor:"#0A0705D9"},feuille:{gap:espaces.md,paddingTop:espaces.sm,paddingHorizontal:espaces.md,backgroundColor:couleurs.surface1,borderTopLeftRadius:rayons.carte,borderTopRightRadius:rayons.carte},poignee:{alignSelf:"center",width:40,height:4,borderRadius:4,backgroundColor:couleurs.bordure},entete:{flexDirection:"row",gap:espaces.sm},titre:{color:couleurs.textePrincipal,fontSize:typo.titre,fontFamily:police.demi},sous:{color:couleurs.texteSecondaire,fontSize:typo.repere,fontFamily:police.normal,marginTop:4},fermer:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:couleurs.surface2},options:{gap:espaces.sm},option:{minHeight:58,flexDirection:"row",alignItems:"center",gap:espaces.sm,padding:espaces.sm,borderRadius:rayons.tuile,backgroundColor:couleurs.surface2},optionTexte:{flex:1,color:couleurs.textePrincipal,fontFamily:police.moyen,fontSize:typo.repere},confirmation:{color:couleurs.texteSecondaire,fontFamily:police.normal,fontSize:typo.corps},erreur:{color:couleurs.fraicheurAVerifier,fontFamily:police.moyen,fontSize:typo.libelle}});
