import { createRoot } from 'react-dom/client'
import { useEffect, useState, type ReactNode } from 'react'
import { ArrowRight, BadgeCheck, Building2, Check, ChevronRight, CircleHelp, Compass, House, MapPin, Menu, MessageCircle, Search, ShieldCheck, Store, X } from 'lucide-react'
import './style.css'
import './trade.css'
import './pricing.css'
import './fauna.css'
import './three.css'
import KoteScene from './components/KoteScene'

const nav = [
  { href: '#/', label: 'Accueil' },
  { href: '#/comment-ca-marche', label: 'Comment ça marche' },
  { href: '#/a-propos', label: 'À propos' },
  { href: '#/professionnels', label: 'Offres pro' },
]

function Brand() { return <a className="brand" href="#/" aria-label="Koté, accueil"><span className="brand-mark"><i>K</i><em /></span><strong>Koté</strong></a> }

function Header({ path }: { path: string }) {
  const [open, setOpen] = useState(false)
  return <header className="site-header">
    <Brand />
    <nav className="desktop-links" aria-label="Navigation principale">
      {nav.map((item) => <a className={path === item.href ? 'active' : ''} href={item.href} key={item.href}>{item.label}</a>)}
    </nav>
    <a className="button button-dark header-action" href="#/professionnels">Ajouter mon commerce <ArrowRight size={16} /></a>
    <button className="menu-button" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    {open && <nav className="drawer" aria-label="Menu mobile">{nav.map((item) => <a href={item.href} onClick={() => setOpen(false)} key={item.href}>{item.label}<ChevronRight size={17} /></a>)}<a href="#/professionnels" onClick={() => setOpen(false)}>Ajouter mon commerce <ArrowRight size={17} /></a></nav>}
  </header>
}

function SearchPreview() { return <div className="search-preview" aria-label="Aperçu d'une recherche Koté"><div className="preview-top"><span>Autour de vous</span><b>Adidogomé</b></div><div className="preview-search"><Search size={18}/><span>Que cherchez-vous ?</span></div><div className="merchant-card"><div className="merchant-avatar orange">A</div><div><b>Atelier Afiavi</b><small><MapPin size={12}/> À 400 m · Couture</small></div><BadgeCheck size={20}/></div><div className="merchant-card"><div className="merchant-avatar blue">K</div><div><b>Chez Kossi</b><small><MapPin size={12}/> En face du carrefour</small></div><ChevronRight size={20}/></div><p className="preview-foot"><span /> Des commerces repérés, pas inventés.</p></div> }

function Hero() { return <><section className="hero-section"><div className="hero-copy"><p className="eyebrow"><i /> Le quartier a ses bonnes adresses</p><h1>Le bon commerce.<br/><em>Juste à côté.</em></h1><p className="hero-lede">Koté aide les habitants de Lomé à retrouver les commerces et artisans réellement actifs autour d’eux.</p><div className="hero-actions"><a className="button button-orange" href="#/comment-ca-marche">Trouver autour de moi <ArrowRight size={18}/></a><a className="text-action" href="#/professionnels">Je tiens un commerce <ArrowRight size={17}/></a></div><p className="hero-note"><ShieldCheck size={17}/> Des informations expliquées et vérifiées quand c’est possible.</p></div><div className="hero-art"><div className="sun"/><span className="art-label one">ADIDOGOMÉ</span><span className="art-label two">BÈ-KLIKAMÉ</span><span className="art-label three">AGOÈ</span><div className="hero-bubble"><Compass size={24}/><span><b>Le quartier,<br/>en clair.</b><small>Un repère utile.</small></span></div><SearchPreview /></div></section><section className="proof-strip"><p><b>Pas de promesse floue.</b> Des fiches, des repères et une discussion directe.</p><div><span><BadgeCheck size={20}/> Fiches suivies</span><span><MessageCircle size={20}/> WhatsApp direct</span><span><MapPin size={20}/> Repères locaux</span></div></section></> }

function Steps() { const steps = [{ n: '01', icon: Search, title: 'Dites ce dont vous avez besoin.', text: 'Un artisan, un commerce, un service à proximité.' }, { n: '02', icon: MapPin, title: 'Situez-le sans vous perdre.', text: 'Les repères du quartier comptent plus qu’une adresse compliquée.' }, { n: '03', icon: MessageCircle, title: 'Écrivez directement.', text: 'Vous échangez avec le commerce sur WhatsApp, simplement.' }]; return <section className="steps-section"><div className="section-heading"><p className="eyebrow"><i /> Trois gestes, c’est tout</p><h2>Moins chercher.<br/><em>Plus trouver.</em></h2></div><div className="steps-grid">{steps.map(({ n, icon: Icon, title, text }) => <article className="step-card" key={n}><span className="step-number">{n}</span><Icon size={28}/><h3>{title}</h3><p>{text}</p></article>)}</div></section> }

function Trust() { return <section className="trust-section"><div className="trust-copy"><p className="eyebrow light"><i /> Une confiance lisible</p><h2>On dit <em>pourquoi</em><br/>une fiche est fiable.</h2><p>Pas de score obscur ni de badge gadget. Koté montre des indices simples, compréhensibles par tous.</p><a className="button button-light" href="#/a-propos">Notre approche <ArrowRight size={17}/></a></div><div className="trust-list"><article><span><BadgeCheck /></span><div><b>Confirmée récemment</b><p>Le commerçant a indiqué que son activité est toujours ouverte.</p></div></article><article><span><ShieldCheck /></span><div><b>Vérifiée sur le terrain</b><p>Un ambassadeur Koté a contrôlé l’activité et le repère.</p></div></article><article><span><CircleHelp /></span><div><b>Informations suivies</b><p>Les signalements reçus sont pris en compte par l’équipe.</p></div></article></div></section> }

function ProfessionalCallout() { return <section className="pro-callout"><div><p className="eyebrow"><i /> Vous tenez un commerce ?</p><h2>Faites-vous trouver<br/><em>par votre quartier.</em></h2><p>Créez une fiche claire, ajoutez votre repère, vos horaires et une photo. Vos clients vous écrivent directement.</p><a className="button button-dark" href="#/professionnels">Créer ma fiche <ArrowRight size={17}/></a></div><div className="pro-stamp"><Building2 size={42}/><b>Votre activité<br/>mérite d’être<br/><em>visible.</em></b><span>LOMÉ · TOGO</span></div></section> }

function Pricing() { const offers = [
  { name: 'Essentiel', price: '0', note: 'Pour être trouvé simplement.', features: ['Fiche commerce', 'Repère & horaires', 'Demandes de contact protégées'] },
  { name: 'Koté Pro', price: '3 000', note: 'Pour développer sa présence locale.', features: ['Tout Essentiel', 'Fiche certifiée sur le terrain', 'Photos et statistiques', 'Mise en avant dans le quartier'], featured: true },
  { name: 'Koté Pro+', price: '7 500', note: 'Pour les commerces déjà structurés.', features: ['Tout Koté Pro', 'Plusieurs points de vente', 'Promotions locales', 'Accompagnement prioritaire'] },
]; return <section className="pricing-section" id="offres"><div className="pricing-intro"><p className="eyebrow"><i /> Une formule qui grandit avec vous</p><h2>Être visible, <em>sans se ruiner.</em></h2><p>Les habitants utilisent Koté gratuitement. Les commerces choisissent le niveau d’accompagnement qui leur correspond.</p></div><div className="pricing-grid">{offers.map((offer) => <article className={offer.featured ? 'pricing-card featured' : 'pricing-card'} key={offer.name}>{offer.featured && <span className="popular">Le choix local</span>}<h3>{offer.name}</h3><p className="price"><b>{offer.price}</b> FCFA <small>/ mois</small></p><p className="pricing-note">{offer.note}</p><ul>{offer.features.map((feature) => <li key={feature}><Check size={15}/>{feature}</li>)}</ul><a className={offer.featured ? 'button button-orange' : 'button button-dark'} href="#/professionnels">Choisir cette formule <ArrowRight size={16}/></a></article>)}</div><p className="certification-note"><BadgeCheck size={18}/><span><b>Certification Koté :</b> une vérification réelle sur le terrain, proposée séparément quand votre fiche est prête.</span></p></section> }

function Home() { return <><div className="hero-three" aria-hidden="true"><KoteScene/></div><Hero/><Steps/><Trust/><ProfessionalCallout/><Pricing/></> }

const content = {
  how: { label: 'Le guide Koté', title: <>Trouver sans tourner<br/><em>en rond.</em></>, lead: 'Koté transforme les bonnes adresses de quartier en fiches utiles : une activité, un repère, une information fraîche et un contact direct.', blocks: [['Cherchez', 'Saisissez ce que vous cherchez ou parcourez les catégories proches.'], ['Vérifiez', 'Lisez les indications simples qui permettent d’évaluer une fiche.'], ['Contactez', 'Un clic vous mène au WhatsApp du commerce ou de l’artisan.']] },
  about: { label: 'À propos', title: <>Le commerce local<br/><em>mérite mieux.</em></>, lead: 'Nous créons un point de rencontre simple entre les habitants et les activités qui font vivre Lomé au quotidien.', blocks: [['Utile avant tout', 'Koté privilégie les informations qui vous aident vraiment à trouver.'], ['Ancré dans Lomé', 'Les repères, les quartiers et les usages locaux ne sont pas des détails.'], ['Une confiance concrète', 'Nous préférons expliquer nos signaux plutôt que distribuer des badges automatiques.']] },
  pro: { label: 'Espace professionnel', title: <>Votre quartier cherche<br/><em>déjà votre activité.</em></>, lead: 'Une fiche Koté donne à vos futurs clients l’essentiel pour vous trouver et vous écrire, sans intermédiaire.', blocks: [['Votre fiche', 'Nom, activité, horaires, repère et photos : vous gardez la main.'], ['Vos clients', 'Un contact direct par WhatsApp, sans commission sur vos échanges.'], ['Votre visibilité', 'Une présence utile là où les habitants cherchent vraiment.']] },
}
function InfoPage({ type }: { type: keyof typeof content }) { const data = content[type]; return <section className="info-page"><div className="info-intro"><p className="eyebrow"><i /> {data.label}</p><h1>{data.title}</h1><p>{data.lead}</p><a className="button button-orange" href={type === 'pro' ? '#/' : '#/professionnels'}>{type === 'pro' ? 'Découvrir Koté' : 'Créer ma fiche'} <ArrowRight size={17}/></a></div><div className="info-blocks">{data.blocks.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p></article>)}</div></section> }
function NotFound() { return <section className="not-found"><p className="eyebrow"><i /> Erreur 404</p><h1>Cette adresse n’est pas<br/><em>dans le quartier.</em></h1><p>La page demandée n’existe pas ou a changé d’emplacement.</p><a className="button button-orange" href="#/">Revenir à l’accueil <ArrowRight size={17}/></a></section> }
function BottomNav({ path }: { path: string }) { const items = [{ href: '#/', label: 'Accueil', icon: House }, { href: '#/comment-ca-marche', label: 'Guide', icon: Compass }, { href: '#/a-propos', label: 'À propos', icon: CircleHelp }, { href: '#/professionnels', label: 'Ma fiche', icon: Store }]; return <nav className="bottom-nav" aria-label="Navigation mobile">{items.map(({ href, label, icon: Icon }) => <a className={path === href ? 'active' : ''} href={href} key={href}><Icon size={20}/><span>{label}</span></a>)}</nav> }
function Footer() { return <footer className="site-footer"><div className="footer-top"><div className="footer-signature"><Brand/><p>Les commerces qui font vivre le quartier, enfin faciles à retrouver.</p><a className="footer-cta" href="#/professionnels">Référencer mon commerce <ArrowRight size={16}/></a></div><div className="footer-links"><div><b>Découvrir</b><a href="#/">Accueil</a><a href="#/comment-ca-marche">Comment ça marche</a><a href="#/a-propos">À propos</a></div><div><b>Commerçants</b><a href="#/professionnels">Créer ma fiche</a><a href="#/professionnels">Les offres pro</a><a href="#/professionnels">Certification</a></div></div></div><div className="footer-bottom"><small>© 2026 Koté. Conçu pour Lomé, Togo.</small><span>Une information locale, une connexion directe.</span></div></footer> }
function App() { const [path, setPath] = useState(location.hash || '#/'); useEffect(() => { const update = () => setPath(location.hash || '#/'); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, []); const page: ReactNode = path === '#/' ? <Home/> : path === '#/comment-ca-marche' ? <InfoPage type="how"/> : path === '#/a-propos' ? <InfoPage type="about"/> : path === '#/professionnels' ? <InfoPage type="pro"/> : <NotFound/>; return <><Header path={path}/><main>{page}</main><Footer/><BottomNav path={path}/></> }
createRoot(document.getElementById('app')!).render(<App />)
